from __future__ import unicode_literals
from django.conf.urls import url
from django.views.generic import TemplateView
import views

app_name = 'django_app'
urlpatterns = [
    url(r'change_password$', views.change_password,
        name='change_password'),
    url(r'all_ready_not_returned_orders$', views.all_ready_not_returned_orders,
        name='all_ready_not_returned_orders'),
    url(r'create_user$', views.create_user,
        name='create_user'),
    url(r'create_client$', views.create_client,
        name='create_client'),
    url(r'create_bonus$', views.create_bonus,
        name='create_bonus'),
    url(r'create_discount$', views.create_discount,
        name='create_discount'),
    url(r'create_service$', views.create_service,
        name='create_service'),
    url(r'update_service/([0-9]+)$', views.update_service,
        name='update_service'),
    url(r'get_bonuses$', views.get_bonuses,
        name='get_bonuses'),
    url(r'update_bonus/([0-9]+)$', views.update_bonus,
        name='update_bonus'),
    url(r'get_discounts$', views.get_discounts,
        name='get_discounts'),
    url(r'update_discount/([0-9]+)$', views.update_discount,
        name='update_discount'),
    url(r'create_office$', views.create_office,
        name='create_office'),
    url(r'update_office/([0-9]+)$', views.update_office,
        name='update_office'),

    # url(r'edit_order/([0-9]+)$', views.edit_order,
    #     name='edit_order'),
    url(r'return_order/([0-9]+)$', views.return_order,
        name='return_order'),
    url(r'set_order_ready_status/([0-9]+)$', views.set_order_ready_status,
        name='set_order_ready_status'),
    url(r'update_client/([0-9]+)$', views.update_client,
        name='update_client'),
    url(r'clients$', views.get_clients,
        name='clients'),
    url(r'offices$', views.get_offices,
        name='offices'),
    url(r'order/([0-9]+)$', views.get_order_info,
        name='order'),
    url(r'check_order$', views.check_order,
        name='check_order'),
    url(r'client_orders/([0-9]+)$', views.client_orders,
        name='client_orders'),
    url(r'check_client_order$', views.check_client_orders,
        name='check_client_orders'),
    url(r'client_orders_ready_not_returned/([0-9]+)$', views.client_orders_ready_not_returned,
        name='ready_not_returned_orders'),
    url(r'check_order_ready_not_returned$', views.check_client_orders_ready_not_returned,
        name='check_client_orders_ready_not_returned'),
    url(r'client_info/([0-9]+)$', views.client_info,
        name='client_info'),
    url(r'check_client_info$', views.check_client_info,
        name='check_client_info'),
    url(r'logout$', views.logout,
        name='logout'),
    url(r'login$', views.login,
        name='login'),
    url(r'register$', views.register,
        name='register'),
    url(r'services$', views.services,
        name='services'),
    url(r'add_order$', views.order,
        name='add_order'),
    url(r'all_orders$', views.all_orders,
        name='all_orders'),
    url(r'$', TemplateView.as_view(template_name='django_app/index.html'),
        name='index'),
]